version: '3.9'
services:
  web:
    build: .
    command: ["go", "run", "./cmd/lp/", "serve"]
    env_file: .envrc
    environment:
      ENV: development
    ports:
     - 8081:8081
    volumes:
      - ./:/app
